on:
  push:
  pull_request:
    branches:
      - master

name: example

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} ${{ matrix.config.msystem }}

    defaults:
      run:
        shell: ${{ matrix.config.shell }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, shell: bash}
          - {os: windows-latest, shell: 'msys2 {0}', msystem: MINGW64 }
          - {os: windows-latest, shell: 'msys2 {0}', msystem: MINGW32 }
          - {os: ubuntu-18.04, shell: bash}
          - {os: ubuntu-16.04, shell: bash}

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          msystem: ${{ matrix.config.msystem }}

      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure && rm config.log

      - name: Make
        run: |
          cd build
          make

      - name: Check
        run: |
          cd build
          make check || ( head -n 1000 *.log && false )
