on:
  push:
  pull_request:
    branches:
      - master

name: example

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, shell: bash}
          - {os: windows-latest, shell: 'mingw64 {0}'}
          - {os: windows-latest, shell: 'mingw32 {0}'}
          - {os: ubuntu-18.04, shell: bash}
          - {os: ubuntu-16.04, shell: bash}

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'

      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure && rm config.log
        shell: ${{ matrix.config.shell }}

      - name: Make
        run: |
          cd build
          make
        shell: ${{ matrix.config.shell }}

      - name: Check
        run: |
          cd build
          make check || ( head -n 1000 *.log && false )
        shell: ${{ matrix.config.shell }}
